### ISSUE TITLE
esp_event_loop.h not present in esp-idf, causes compliation to fail

### ISSUE THREAD

**Issue by lakidd** [espressif/esp-idf-template#1]
Hi
When using the template yesterday, the app compiled fine.
When cloning and using tonight I get 
/Users/xxx/esp32/myeclipseesp32app2/main/./main.c:5:28: fatal error: esp_event_loop.h: No such file or directory
 #include "esp_event_loop.h"
And sure enough, the file isn't anywhere on my system.
Am I missing something ? This is OS X btw

**Comment by igrr** [comment]
Please try doing `git pull origin master` on esp-idf, that should fix it.
