### ISSUE TITLE
Restrictive license on this template

### ISSUE THREAD

**Issue by Sonophoto** [espressif/esp-idf-template#2]
So EVERY project built with this template has to use the Apache License???

Seems like reference designs are supposed to be unlicensed or PD to actually be useful to businesses.

Please clarify.

**Comment by Spritetm** [comment]
That may be an oversight on our part, I think all of our other examples are CC0/public domain.

**Comment by Sonophoto** [comment]
Well I'll check back Monday and see if it is updated. Legal says BSD 2c, PD or NO GO. This is a commercial project. There is already a LOT of uphill on this ESP32 device. We ordered them 2 months ago and still don't have them...

Thanks for your Quick Response! :-)

**Comment by igrr** [comment]
License updated to public domain / CC0 in 9e3618ee0d1bd0fdcde51225276fa9ab00c65a99.

**Comment by Sonophoto** [comment]
Nice! I dont work for that company anymore but ESP32 grew up! Awesome system, I just bought a WROVER dev kit.
